# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f62e3e86b611640105b17904f6fb68383ba51d28d18f6cf5ab11aef84c28752de86b23fd0fef719915439e06038d8bbd9d039e3841be41debb6047a1fe433753

test:
  secret_key_base: 9b2bd303ed543af909b6daa21fb4294ab65bf09650a74ac1994e5c5ba2374c5f00de595479a0741ae7cf0b745f6ad2e5ad82b4cef304244ac3d9efd8d485a364

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
